# -*- mode: ruby -*-
# vi: set ft=ruby :

st2ver   = ENV['ST2VER'] ? ENV['ST2VER'] : '0.8.0'
webui    = ENV['WEBUI'] ? ENV['WEBUI'] : '1'
hostname = ENV['HOSTNAME'] ? ENV['HOSTNAME'] : 'st2express'

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

if !Vagrant.has_plugin?('vagrant-proxyconf') && !ENV['WITH_VAGRANT_PROXY'].nil?
  fail "
  *******                                                          *******
    Using vagrant-proxyconf setup.  Please install vagrant-proxyconf,

    \$ vagrant plugin install vagrant-proxyconf

    and run with command :

    \$ WITH_VAGRANT_PROXY=true vagrant up
  *******                                                          *******
  "
end
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

    # proxy setup if configured
    # Setting the proxy action up
    if Vagrant.has_plugin?('vagrant-proxyconf')
      config.proxy.https = ENV['HTTPS_PROXY'] unless ENV['HTTPS_PROXY'].nil?
      config.proxy.http = ENV['HTTP_PROXY'] unless ENV['HTTP_PROXY'].nil?
      config.proxy.no_proxy = ENV['NO_PROXY'].nil? ? ENV['NO_PROXY'] : \
                              'localhost,127.0.0.1,10.0.0.1,169.254.169.254'
    end

    config.vm.box = "ubuntu/trusty64"
    config.vm.hostname = "#{hostname}"

    config.vm.define "#{hostname}" do |q|
    end

    config.vm.provider :virtualbox do |vb|
      vb.name = "#{hostname}"
      vb.memory = 2048
      vb.cpus = 1
    end

    # Configure a private network
    config.vm.network "private_network", ip: "172.168.90.50"

    # Start shell provisioning
    config.vm.provision :shell, :inline => "curl -sS -k -O https://ops.stackstorm.net/releases/st2/scripts/st2_deploy.sh"
    config.vm.provision :shell, :inline => "INSTALL_WEBUI=#{webui} bash -c '. st2_deploy.sh #{st2ver}'"
    config.vm.provision :shell, :path => "rsyslog.sh"
    #config.vm.provision :shell, :path => "sensu_server.sh"
    #config.vm.provision :shell, :path => "sensu_client.sh"
    config.vm.provision :shell, :inline => "INSTALL_WEBUI=#{webui} bash -c '/vagrant/validate.sh'"
end
